INSERT INTO "kota" ("id_kota", "kota") VALUES (1, 'Banda Aceh');
INSERT INTO "kota" ("id_kota", "kota") VALUES (2, 'Medan');
INSERT INTO "kota" ("id_kota", "kota") VALUES (3, 'Palembang');
INSERT INTO "kota" ("id_kota", "kota") VALUES (4, 'Padang');
INSERT INTO "kota" ("id_kota", "kota") VALUES (5, 'Bengkulu');
INSERT INTO "kota" ("id_kota", "kota") VALUES (6, 'Pekanbaru');
INSERT INTO "kota" ("id_kota", "kota") VALUES (7, 'Tanjung Pinang');
INSERT INTO "kota" ("id_kota", "kota") VALUES (8, 'Jambi');
INSERT INTO "kota" ("id_kota", "kota") VALUES (9, 'Bandar Lampung');
INSERT INTO "kota" ("id_kota", "kota") VALUES (10, 'Pangkal Pinang');
INSERT INTO "kota" ("id_kota", "kota") VALUES (11, 'Pontianak');
INSERT INTO "kota" ("id_kota", "kota") VALUES (12, 'Samarinda');
INSERT INTO "kota" ("id_kota", "kota") VALUES (13, 'Banjarmasin');
INSERT INTO "kota" ("id_kota", "kota") VALUES (14, 'Palangkaraya');
INSERT INTO "kota" ("id_kota", "kota") VALUES (15, 'Tanjung Selor');
INSERT INTO "kota" ("id_kota", "kota") VALUES (16, 'Serang');
INSERT INTO "kota" ("id_kota", "kota") VALUES (17, 'Jakarta');
INSERT INTO "kota" ("id_kota", "kota") VALUES (18, 'Bandung');
INSERT INTO "kota" ("id_kota", "kota") VALUES (19, 'Semarang');
INSERT INTO "kota" ("id_kota", "kota") VALUES (20, 'Surabaya');
INSERT INTO "kota" ("id_kota", "kota") VALUES (21, 'Yogyakarta');
INSERT INTO "kota" ("id_kota", "kota") VALUES (22, 'Denpasar');
INSERT INTO "kota" ("id_kota", "kota") VALUES (23, 'Kupang');
INSERT INTO "kota" ("id_kota", "kota") VALUES (24, 'Mataram');
INSERT INTO "kota" ("id_kota", "kota") VALUES (25, 'Gorontalo');
INSERT INTO "kota" ("id_kota", "kota") VALUES (26, 'Mamuju');
INSERT INTO "kota" ("id_kota", "kota") VALUES (27, 'Palu');
INSERT INTO "kota" ("id_kota", "kota") VALUES (28, 'Manado');
INSERT INTO "kota" ("id_kota", "kota") VALUES (29, 'Kendari');
INSERT INTO "kota" ("id_kota", "kota") VALUES (30, 'Makassar');
INSERT INTO "kota" ("id_kota", "kota") VALUES (31, 'Sofifi');
INSERT INTO "kota" ("id_kota", "kota") VALUES (32, 'Ambon');
INSERT INTO "kota" ("id_kota", "kota") VALUES (33, 'Manokwari');
INSERT INTO "kota" ("id_kota", "kota") VALUES (34, 'Jayapura');
INSERT INTO "kota" ("id_kota", "kota") VALUES (35, 'Nabire');
INSERT INTO "kota" ("id_kota", "kota") VALUES (36, 'Jayawijaya');
INSERT INTO "kota" ("id_kota", "kota") VALUES (37, 'Merauke');
INSERT INTO "kota" ("id_kota", "kota") VALUES (38, 'Sorong');
